apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: dupvipmonitor
  name: dupvipmonitor
spec:
  replicas: 1
  selector:
    deploymentconfig: dupvipmonitor
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        app: dupvipmonitor
        deploymentconfig: dupvipmonitor
      name: dupvipmonitor
      namespace: TEST_NAMESPACE
    spec:
      containers:
      - image: TEST_DOCKER_REGISTRY/TEST_NAMESPACE/dupvipmonitor:v1
        env:
        - name: MONITOR_VIPS
          value: TEST_VIPS
        imagePullPolicy: Always
        name: dupvipmonitor
        ports:
        - containerPort: 23333
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 125m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        dupvipmonitor: "true"
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccount: dupvipmonitor
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dupvipmonitor
  name: dupvipmonitor
spec:
  ports:
  - name: proxy23333by80
    port: 80
    protocol: TCP
    targetPort: 23333
  selector:
    app: dupvipmonitor
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: dupvipmonitor
  name: dupvipmonitor
  namespace: TEST_NAMESPACE
spec:
  host: TEST_ROUTE
  to:
    kind: Service
    name: dupvipmonitor
    weight: 100
  wildcardPolicy: None
