apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    app: vipchecker
  name: vipchecker
spec:
  replicas: 1
  selector:
    deploymentconfig: vipchecker
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vipchecker
        deploymentconfig: vipchecker
      name: vipchecker
      namespace: zp1dev
    spec:
      containers:
      - image: harbor.testos39.com/zp1dev/vipchecker:v1
        command: ["sh", "-c", "echo hello; sleep 3000"]
        imagePullPolicy: Always
        name: vipchecker
        ports:
        - containerPort: 23333
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 125m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccount: vipmonitor
